title: "404 Brain Not Found"
description: "Still learning. Still glitching"
url: "https://fightMMC0lub.github.io"
baseurl: ""

author:
  name: "3#31200xsN"

theme: minima

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/


include:
  - _pages
